name: linux_do
description: A Linux Discourse client.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1
license: MIT
repository: https://github.com/R-lz/LINUX-DO

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  
  keframe: ^3.0.0
  lazy_load_indexed_stack: ^1.2.1
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.1
  retrofit: ^4.0.3
  dio: ^5.4.0
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  logger: ^2.5.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.4
  permission_handler: ^11.3.1 
  device_info_plus: ^9.1.1
  package_info_plus: ^8.1.3
  convex_bottom_bar: ^3.2.0
  flutter_slidable: ^3.0.1
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0
  flutter_html: ^3.0.0-beta.2
  flutter_html_table: ^3.0.0-beta.2
  flutter_layout_grid: ^2.0.7
  path_provider: ^2.1.2
  flutter_inappwebview: ^6.1.5
  slide_switcher: ^1.1.2
  dropdown_search: ^6.0.2
  scrollable_positioned_list: ^0.3.8
  photo_view: ^0.15.0
  image_picker: ^1.0.7
  crypto: ^3.0.3
  # emoji_picker_flutter: ^4.3.0
  calendar_date_picker2: ^1.1.8
  image_gallery_saver:
    git:
      url: https://github.com/R-lz/image_gallery_saver.git
      ref: 467f4dcbce79c0779290a53b00d44efee027805c
  file_picker: ^8.3.3
  url_launcher: ^6.3.1
  flutter_markdown: ^0.6.18+2
  flutter_highlighter: ^0.1.1
  markdown: ^7.2.1
  font_awesome_flutter: ^10.7.0
  flutter_custom_tabs: ^2.1.0
  mobile_scanner: ^3.5.6
  video_player: ^2.9.3
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.6.2
  uuid: ^4.3.3
  expandable_page_view: ^1.0.17
  flutter_svg: ^2.0.17
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator: ^8.0.6
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/light/
    - assets/images/dark/
    - assets/json/
    - assets/html/
    - assets/icons/
  fonts:
    - family: DINPro
      fonts:
        - asset: assets/fonts/digital/D-DIN-PRO-Regular.otf
        - asset: assets/fonts/digital/D-DIN-PRO-Medium.otf
        - asset: assets/fonts/digital/D-DIN-PRO-Bold.otf
        - asset: assets/fonts/digital/D-DINExp.otf
