name: 功能请求 Feature Request
description: 为这个项目提出一个想法或建议
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        感谢你为项目提出新的功能建议！
  
  - type: textarea
    id: problem
    attributes:
      label: 相关问题
      description: 新增增加什么功能或者优化那些地方
      placeholder: 我希望增加...功能或者优化...
    validations:
      required: true
      
  - type: input
    id: app_version
    attributes:
      label: 当前版本
      placeholder: 例如 1.0.1
    validations:
      required: true
      
  - type: textarea
    id: additional
    attributes:
      label: 其他信息
      description: 任何其他相关的上下文或截图
    validations:
      required: false 