name: Build Android
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.27.2'
      - name: Accept Android SDK licenses
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
      - name: Install Android platforms
        run: |
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-33"
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-34"
      
      - name: Configure build.gradle for app
        run: |
          sed -i 's/minSdkVersion .*/minSdkVersion 21/' android/app/build.gradle
          sed -i 's/targetSdkVersion .*/targetSdkVersion 34/' android/app/build.gradle
          sed -i 's/compileSdkVersion .*/compileSdkVersion 34/' android/app/build.gradle
      - name: Get dependencies
        run: flutter pub get
      - name: Create fix script
        run: |
          cat > fix_plugin.sh << 'EOF'
          #!/bin/bash

          # 使用绝对路径
          PLUGIN_DIR="/home/runner/.pub-cache/hosted/pub.dev/image_gallery_saver-2.0.3"
          MANIFEST_FILE="$PLUGIN_DIR/android/src/main/AndroidManifest.xml"
          BUILD_GRADLE="$PLUGIN_DIR/android/build.gradle"
          
          echo "检查文件..."
          if [ ! -f "$MANIFEST_FILE" ]; then
            echo "未找到 AndroidManifest.xml"
            find /home/runner/.pub-cache -name "AndroidManifest.xml" | grep image_gallery_saver
            exit 1
          fi
          
          if [ ! -f "$BUILD_GRADLE" ]; then
            echo "未找到 build.gradle"
            find /home/runner/.pub-cache -name "build.gradle" | grep image_gallery_saver
            exit 1
          fi
          
          echo "备份文件..."
          cp "$MANIFEST_FILE" "${MANIFEST_FILE}.bak"
          cp "$BUILD_GRADLE" "${BUILD_GRADLE}.bak"
          
          echo "修改AndroidManifest.xml..."
          sed -i 's/package="[^"]*"//g' "$MANIFEST_FILE"
          
          echo "修改build.gradle..."
          # 修改compileSdkVersion为34
          sed -i 's/compileSdkVersion [0-9]*/compileSdkVersion 34/g' "$BUILD_GRADLE"
          
          if grep -q "android {" "$BUILD_GRADLE"; then
            # 检查是否已有namespace
            if grep -q "namespace" "$BUILD_GRADLE"; then
              echo "已存在namespace，无需修改"
            else
              # 在android {之后添加namespace行
              echo "添加namespace到android块..."
              # 创建一个临时文件
              TEMP_FILE="${BUILD_GRADLE}.temp"
              # 用awk添加namespace行
              awk '/android {/ {print $0; print "    namespace \"com.example.imagegallerysaver\""; next} {print}' "$BUILD_GRADLE" > "$TEMP_FILE"
              # 替换原文件
              mv "$TEMP_FILE" "$BUILD_GRADLE"
            fi
          else
            # 如果没有android块，添加完整块
            echo "添加完整android块..."
            echo "android {" >> "$BUILD_GRADLE"
            echo "    namespace \"com.example.imagegallerysaver\"" >> "$BUILD_GRADLE"
            echo "    compileSdkVersion 34" >> "$BUILD_GRADLE"
            # 添加解决lStar问题的配置
            echo "    defaultConfig {" >> "$BUILD_GRADLE"
            echo "        resConfigs \"en\", \"xxhdpi\"" >> "$BUILD_GRADLE"
            echo "    }" >> "$BUILD_GRADLE"
            echo "    buildFeatures {" >> "$BUILD_GRADLE"
            echo "        renderScript false" >> "$BUILD_GRADLE"
            echo "        aidl false" >> "$BUILD_GRADLE"
            echo "        buildConfig true" >> "$BUILD_GRADLE"
            echo "    }" >> "$BUILD_GRADLE"
            echo "}" >> "$BUILD_GRADLE"
          fi
          
          # 统一Java和Kotlin编译目标
          echo "统一Java和Kotlin编译目标..."
          
          # 检查Kotlin插件是否应用
          if grep -q "kotlin-android" "$BUILD_GRADLE"; then
            echo "Kotlin插件已应用，添加kotlinOptions配置..."
            # 添加或更新kotlinOptions
            if grep -q "kotlinOptions" "$BUILD_GRADLE"; then
              # 已有kotlinOptions块，更新jvmTarget
              sed -i '/kotlinOptions {/,/}/{s/jvmTarget.*/jvmTarget = "1.8"/g}' "$BUILD_GRADLE"
              if ! grep -q "jvmTarget" "$BUILD_GRADLE"; then
                # 如果kotlinOptions块中没有jvmTarget，添加它
                sed -i '/kotlinOptions {/a \        jvmTarget = "1.8"' "$BUILD_GRADLE"
              fi
            else
              # 没有kotlinOptions块，添加完整块
              if grep -q "android {" "$BUILD_GRADLE"; then
                # 在android块末尾添加kotlinOptions
                TEMP_FILE="${BUILD_GRADLE}.temp"
                awk '/android {/{flag=1} flag && /}/{print $0; print "    kotlinOptions {"; print "        jvmTarget = \"1.8\""; print "    }"; flag=0; next} {print}' "$BUILD_GRADLE" > "$TEMP_FILE"
                mv "$TEMP_FILE" "$BUILD_GRADLE"
              fi
            fi
          fi
          
          # 确保Java编译目标也是1.8
          if ! grep -q "compileOptions" "$BUILD_GRADLE"; then
            # 如果没有compileOptions块，添加它
            if grep -q "android {" "$BUILD_GRADLE"; then
              # 在android块末尾添加compileOptions
              TEMP_FILE="${BUILD_GRADLE}.temp"
              awk '/android {/{flag=1} flag && /}/{print $0; print "    compileOptions {"; print "        sourceCompatibility JavaVersion.VERSION_1_8"; print "        targetCompatibility JavaVersion.VERSION_1_8"; print "    }"; flag=0; next} {print}' "$BUILD_GRADLE" > "$TEMP_FILE"
              mv "$TEMP_FILE" "$BUILD_GRADLE"
            fi
          else
            # 如果有compileOptions块，确保设置正确
            sed -i '/compileOptions {/,/}/{s/sourceCompatibility.*/sourceCompatibility JavaVersion.VERSION_1_8/g}' "$BUILD_GRADLE"
            sed -i '/compileOptions {/,/}/{s/targetCompatibility.*/targetCompatibility JavaVersion.VERSION_1_8/g}' "$BUILD_GRADLE"
          fi
          
          # 添加androidx依赖以解决可能的兼容性问题
          if ! grep -q "androidx.appcompat:appcompat" "$BUILD_GRADLE"; then
            echo "添加androidx依赖..."
            echo "dependencies {" >> "$BUILD_GRADLE"
            echo "    implementation \"androidx.appcompat:appcompat:1.6.1\"" >> "$BUILD_GRADLE"
            echo "    implementation \"androidx.core:core-ktx:1.12.0\"" >> "$BUILD_GRADLE"
            echo "}" >> "$BUILD_GRADLE"
          fi
          
          echo "修改完成!"
          echo "AndroidManifest.xml内容:"
          cat "$MANIFEST_FILE"
          echo "build.gradle内容:"
          cat "$BUILD_GRADLE"
          EOF
          
          chmod +x fix_plugin.sh
      - name: Fix image_gallery_saver
        run: ./fix_plugin.sh
      - name: Run code generation
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Build APK
        run: flutter build apk --release --split-per-abi --no-sign
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: build/app/outputs/apk/release/*
