name: Build Android

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.27.2'

      - name: Accept Android SDK licenses
        run: flutter doctor --android-licenses -v

      - name: Install Android platform 33
        run: flutter config --android-sdk $ANDROID_HOME && yes | flutter doctor --android-licenses && $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-33"

      - name: Configure build.gradle
        run: |
          sed -i 's/minSdkVersion .*/minSdkVersion 21/' android/app/build.gradle
          sed -i 's/targetSdkVersion .*/targetSdkVersion 33/' android/app/build.gradle

      - name: Get dependencies
        run: flutter pub get

      - name: Run code generation
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: build/app/outputs/apk/release/*
