name: Build Android APK (Forked Project)

on:
  push:
    branches: [ "main" ] # 或者你想要触发构建的分支名称
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest # 或者选择其他 Linux runner

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: flutter-actions/setup-flutter@v2
        with:
          flutter-version: '3.0.1' # 指定 Flutter 版本范围

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Install Android SDK
        run: |
          sudo apt-get update -y
          sudo apt-get install -y android-sdk

      - name: Set up Android SDK environment
        run: |
          echo "sdk.dir=${ANDROID_SDK_ROOT}" > local.properties
          echo 'flutter.sdk=/opt/flutter' >> local.properties
          echo yes | sdkmanager --licenses || true

          # 使用 bash 的 profile 文件设置环境变量
          echo 'export ANDROID_HOME=$ANDROID_SDK_ROOT' >> ~/.bash_profile
          echo 'export PATH="$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/tools"' >> ~/.bash_profile
          source ~/.bash_profile # 激活 profile 文件

          # 安装 Android SDK platform 31 和 build-tools 31.0.0
          sdkmanager "platforms;android-31"
          sdkmanager "build-tools;31.0.0"
