name: Build Android APK (Forked Project)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install and Configure Android SDK
        uses: android-actions/setup-android@v3
        with:
          jdkRoot: /usr/lib/jvm/java-11-openjdk-amd64
          sdkCommandToolsVersion: "latest" # 或者指定一个特定版本，如 "7.0"
          components: |
            platforms;android-31
            build-tools;31.0.0
            cmdline-tools;latest
        env:
          SKIP_JDK_VERSION_CHECK: true  # 添加此环境变量

      - name: Accept Android SDK Licenses
        run: |
          echo yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Set up local.properties
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          echo 'flutter.sdk=/opt/flutter' >> local.properties

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --split-per-abi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/apk/release/
