name: Build Android APK (Forked Project)

on:
  push:
    branches: [ "main" ] # 或者你想要触发构建的分支名称
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest # 或者选择其他 Linux runner

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: flutter-actions/setup-flutter@v2
        with:
          flutter-version: '3.0.1' # 指定 Flutter 版本范围

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Install Android SDK
        run: |
          sudo apt-get update -y
          sudo apt-get install -y android-sdk

      - name: Set up Android SDK environment
        run: |
          echo "sdk.dir=${ANDROID_SDK_ROOT}" > local.properties
          echo 'flutter.sdk=/opt/flutter' >> local.properties
          echo yes | sdkmanager --licenses || true
          export ANDROID_HOME=$ANDROID_SDK_ROOT
          export PATH="$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/tools"
          sdkmanager "platforms;android-31"
          sdkmanager "build-tools;31.0.0"

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --split-per-abi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/apk/release/
