name: Build Android

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.27.2'

      - name: Accept Android SDK licenses
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install Android platform 33
        run: $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-33"

      - name: Configure build.gradle for app
        run: |
          sed -i 's/minSdkVersion .*/minSdkVersion 21/' android/app/build.gradle
          sed -i 's/targetSdkVersion .*/targetSdkVersion 33/' android/app/build.gradle

      - name: Get dependencies
        run: flutter pub get

      - name: Debug pub cache location
        run: |
          echo "PUB_CACHE: $PUB_CACHE"
          echo "HOME: $HOME"
          ls -la $HOME/.pub-cache || echo "Default pub cache not found"
          ls -la $PUB_CACHE || echo "PUB_CACHE not set or empty"

      - name: Patch image_gallery_saver build.gradle
        run: |
          PUB_CACHE_DIR=${PUB_CACHE:-"$HOME/.pub-cache"}
          echo "Using PUB_CACHE_DIR: $PUB_CACHE_DIR"
          echo "android { namespace 'com.example.image_gallery_saver' }" > temp.gradle
          find "$PUB_CACHE_DIR/hosted/pub.dartlang.org" -name "build.gradle" -path "*/image_gallery_saver/android/*" -exec sh -c "cat temp.gradle >> {}" \; || echo "Failed to find image_gallery_saver build.gradle"
          rm temp.gradle

      - name: Run code generation
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: build/app/outputs/apk/release/*
